config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'application#index'
    resources :skills
    resources :users
  end

  root 'static_pages#home'

  devise_for :users

  resources :users, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/skill.rb
class Skill < ApplicationRecord

	validates :name, presence: true, uniqueness: {case_sensitive: false}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login

  after_create :send_welcome_email

  validates :username, presence: true, uniqueness: { case_sensitive: false },
    format: { with: /\A[a-zA-Z0-9_\.]*\z/ },
    length: { minimum: 6, allow_blank: true }

  def country_name
    country = ISO3166::Country[country_code]
    country.translations[I18n.locale.to_s] || country.name
  end

  private

  def send_welcome_email
    WelcomeMailer.welcome_email(self).deliver
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      query = 'lower(username) = :value OR lower(email) = :value'
      where(conditions.to_h).where(query, { value: login.downcase }).first
    end
  end


end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController

	before_action :check_user
  
  def index

  end

  private 

  def check_user
  	authenticate_user!

  	if !current_user.admin?
  		redirect_to root_path, alert: "You do not have access to that page!"
  	end
  end

end

app/controllers/admin/skills_controller.rb
class Admin::SkillsController < Admin::ApplicationController

	def index
		@skills = Skill.all
	end

	def new
		@skill = Skill.new
	end

	def create
		@skill = Skill.new(skills_params)
		if @skill.save
			flash[:success] = "The skill was added"
			redirect_to admin_skills_path
		else
			flash[:warning] = "The skill was not added"
			render 'new'
		end
	end

	private
		def skills_params
			params.require(:skill).permit(:name)
		end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController

	before_action :get_user, only: [:edit, :destroy, :update]
  
  def index
  	@users = User.all
  end

  def edit
  end

  def destroy
  	@user.destroy
  	flash[:success] = "User Successfully Deleted!"
  	redirect_to admin_users_path
  end

  def update
  	if @user.update(user_params)
  		flash[:success] = "User Successfully Updated!"
  		redirect_to admin_root_path
  	else
  		flash[:warning] = "User Not Updated"
  		render "edit"
  	end
  end

  private 

  	def user_params
  		params.require(:user).permit(:email, :username)
  	end

  	def get_user
  		@user = User.find(params[:id])
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
	end

	def edit
		if current_user.id == params[:id].to_i
			@user = User.find(params[:id])
		else
			flash[:danger] = "You don't have access to that page"
			redirect_to root_path
		end
	end

	def update
		@user = User.find(params[:id])
		@user.update_attributes(user_params)
		flash[:success] = "Your profile has been updated"
		redirect_to @user
	end

	private

		def user_params
			params.require(:user).permit(:country_code)
		end
end

app/helpers/admin/application_helper.rb
module Admin::ApplicationHelper
end

app/helpers/admin/skills_helper.rb
module Admin::SkillsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/application/index.html.erb
<div class="row">
	<div class="col-md-9">
		<header>
			<h1>Code Connection Admin Home Page</h1>
		</header>
	<div>
	<dlv class="col-md-3">
		<h1>Admin Links</h1>
		<ul class="nav nav-stacked">
			<li><%= link_to "Users Index", admin_users_path %>/li>
		</ul>
	</dlv>
</div>

app/views/admin/skills/index.html.erb
<%= @skills.each do |skill| %>
	<%= skill %>
<% end %>

app/views/admin/skills/new.html.erb
<% if @skill.errors.any? %>
	<% @skill.errors.full_messages.each do |msg| %>
		<%= msg %>
	<% end %>
<% end %>
<%= form_for [:admin, @skill] do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.submit "Add Skill" %>
<% end %>

app/views/admin/users/edit.html.erb
<% if @user.errors.any? %>
	<% @user.errors.full_messages.each do |msg| %>
		<%= msg %>
	<% end %>
<% end %>

<%= form_for [:admin, @user] do |f| %>

	<div class="form-group">
	<%= f.email_field :email, autofocus: true, :class => 'form-control', :placeholder => 'Email' %>
	</div>

	<div class="form-group">
	<%= f.text_field :username, :class => 'form-control', :placeholder => 'Username' %>
	</div>

	<div class="action">
	<%= f.submit "Update User" %>
	</div>
<% end %>

app/views/admin/users/index.html.erb
<h1>List of Users</h1>
<ul>
	<% @users.each do |user| %>
		<li>
			<%= content_tag(:div, id: user.id) do %>
				<%= user.username %>
				<%= link_to "Edit User", edit_admin_user_path(user) %>
				<% unless user.admin? %>
					<%= link_to "Delete User", admin_user_path(user), method: :delete, data: {confirm: "Are you sure you want to delete this user?"} %>
				<% end %>
			<% end %>
		</li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodeConnection</title>
    <%= csrf_meta_tags %>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, value| %>
      <%= value %>
    <% end %>
    <%= render 'shared/navbar' %>


    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<!-- _navbar.html.erb -->
<link href="https://fonts.googleapis.com/css?family=Kranky" rel="stylesheet">
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <span><%= link_to image_tag("https://cloud.githubusercontent.com/assets/25189972/23142797/c240f1d6-f78b-11e6-8a86-24c99b6b2e3a.png", id: 'icon'), root_path,  class: "navbar-brand" %></span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>

        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
          <% if current_user.admin? %>
            <li><a href="#">Admin Home</a></li>
          <% end %>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/static_pages/home.html.erb
<div class="site-wrapper">
  <div class="cover-container">
    <div class="cover">
      <h1 class="title">Welcome to Code Connection</h1>
      <br />
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Edit Your Profile - <%= @user.username %></h1>
<%= form_for(@user) do |f| %>

	<%= f.label :country_code, "Select Country" %>
	<%= f.country_select :country_code %>

	<%= f.submit "Update Profile" %>
<% end %>

app/views/users/show.html.erb
Profile page of <%= @user.username %>

<%= @user.country_name %>
<% if current_user.id == @user.id %>
	<%= link_to "Edit Your Profile", edit_user_path(@user) %>
<% end %>